export const tags = [
  "pop",
  "news",
  "music",
  "rock",
  "classical",
  "talk",
  "radio",
  "estación",
  "méxico",
  "public radio",
  "fm",
  "música",
  "christian",
  "dance",
  "jazz",
  "oldies",
  "top 40",
  "80s",
  "electronic",
  "mex",
  "mx",
  "entretenimiento",
  "mexico",
  "classic rock",
  "90s",
  "pop music",
  "moi merino",
  "hits",
  "música en español",
  "norteamérica",
  "folk",
  "adult contemporary",
  "country",
  "latinoamérica",
  "local news",
  "community radio",
  "alternative",
  "español",
  "classic hits",
  "house",
  "greek",
  "regional mexican",
  "musica",
  "pop rock",
  "música pop",
  "70s",
  "regional",
  "regional radio",
  "música popular mexicana",
  "música regional",
  "regional mexicana",
  "grupera",
  "indie",
  "musica regional mexicana",
  "mexican music",
  "npr",
  "chillout",
  "soul",
  "information",
  "hiphop",
  "musica regional",
  "traditional mexican music",
  "metal",
  "noticias",
  "ambient",
  "university radio",
  "commercial",
  "musica mexicana",
  "musica tradicional mexicana",
  "news talk",
  "techno",
  "lounge",
  "juvenil",
  "talk & speech",
  "sport",
  "culture",
  "misc",
  "grupero",
  "musica latina",
  "funk",
  "sports",
  "regional music",
  "alternative rock",
  "variety",
  "música del recuerdo",
  "rap",
  "disco",
  "latin pop",
  "entertainment",
  "world music",
  "electro",
  "banda",
  "local music",
  "blues",
  "religion",
  "college radio",
  "rnb",
  "am",
  "local radio",
  "musica latinoamericana",
];
